# Generated by Django 4.2 on 2023-04-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingdom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novotestamento',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
